import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased bg-white text-black min-h-screen flex flex-col`}
      >
        <Navbar />
        <main className="flex flex-col lg:flex-row lg:overflow-hidden justify-center items-center w-full flex-grow px-0">
          <div className="w-full lg:w-max h-full lg:h-max">{children}</div>
        </main>
      </body>
    </html>
  );
}
